services:
  - type: web
    name: blockchain-blast
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node src/wallet/webServer.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: RECOVERY_WALLET
        value: 0xb559d5fe73e7d4205db83b01a8b5f349345378fb
